name: Sync Fork with Upstream

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "mdsriqb@gmail.com"
          git config --global user.name "Mudassar Iqbal"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/sign-language-translator/slt-frontend.git
          git fetch upstream

      - name: Merge Upstream changes
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
